name = "ConnectFourSolver"
uuid = "c01be385-ab27-4b9c-92b7-2e6a77fbe7c3"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
ConnectFourSolver_jll = "5ab91c8a-5c16-538d-97cb-84915cefd4b0"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ConnectFourSolver_jll = "0.1"
CxxWrap = "0.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
